from playwright.sync_api import sync_playwright, expect
import re
from typing import List, Dict, Any

class PlaywrightExecutor:
    """Executes generated Playwright actions and assertions in a headless browser environment."""

    def __init__(self, headless: bool = True):
        # Sets whether the browser will run with a visible UI or in the background
        self.headless = headless

    def execute_test(self, test_steps: List[Dict[str, Any]]) -> Dict[str, Any]:
        # Dictionary to track the outcome of the test run
        results = {
            "status": "PASS",
            "steps_executed": 0,
            "error": None
        }

        with sync_playwright() as p:
            # Launching the Chromium browser
            browser = p.chromium.launch(headless=self.headless)
            context = browser.new_context()
            page = context.new_page()

            try:
                for step in test_steps:
                    # Run each individual action and its assertions
                    print(f"Executing step: {step.get('action')} -> {step.get('target')}")
                    self._execute_step(page, step)
                    results["steps_executed"] += 1
            except Exception as e:
                # Capture errors if a step fails
                print(f"Error executing step: {e}")
                results["status"] = "FAIL"
                results["error"] = str(e)
            finally:
                # Ensure resources are cleaned up
                browser.close()

        return results

    def _execute_step(self, page, step: Dict[str, Any]):
        action = step.get("action")
        target = step.get("target")
        value = step.get("value")
        
        # Some formats might put params in a 'params' dict
        if "params" in step:
            params = step["params"]
            target = params.get("target", target)
            value = params.get("value", value)

        assertions = step.get("assertions", [])

        # Map abstract instructions to actual Playwright browser commands
        if action == "open":
            page.goto(target)
        elif action == "click":
            # Wait for element to be actionable
            page.wait_for_selector(target, state="visible", timeout=5000)
            page.click(target)
        elif action == "fill":
            page.wait_for_selector(target, state="visible", timeout=5000)
            page.fill(target, value)
        elif action == "wait":
            page.wait_for_timeout(int(value))
        elif action == "assert":
            # Handled by assertions loop below, but explicitly listed action
            pass

        # Dynamically run the assertion code generated by the LLM
        # We use exec/eval carefully here. 'page', 'expect', and 're' must be available.
        for assertion in assertions:
            # Simple security check to prevent completely arbitrary code if needed, 
            # though this is a local dev tool.
            if assertion.strip().startswith("expect("):
                try:
                    # using eval for single expression assertions
                    eval(assertion, {"expect": expect, "page": page, "re": re})
                    print(f"  Assertion passed: {assertion}")
                except AssertionError as e:
                    raise AssertionError(f"Assertion failed: {assertion}") from e
                except Exception as e:
                    raise RuntimeError(f"Failed to evaluate assertion '{assertion}': {e}") from e

if __name__ == "__main__":
    # Example usage
    try:
        executor = PlaywrightExecutor(headless=False) # Run headed to see it work
        
        # Sample steps similar to what assign2.py + assign3.py would produce
        sample_steps = [
            {
                "action": "open",
                "target": "https://practice.automationtesting.in/",
                "assertions": [
                    "expect(page).to_have_title(re.compile('Automation Practice Site'))"
                ]
            },
            {
                "action": "click",
                "target": "#menu-item-40", # Shop link
                "assertions": [
                    "expect(page).to_have_url(re.compile('.*shop.*'))"
                ]
            }
        ]
        
        print("Starting test execution...")
        result = executor.execute_test(sample_steps)
        print("\nTest Results:")
        print(result)
        
    except Exception as e:
        print(f"Execution failed: {e}")
